version: "3.3"

services:
    sut:
        container_name: test-bench
        image: ${IMAGE_TAG}
        environment:
            TEST_ADDR: ${TEST_ADDR}
        volumes:
            - ./test.sh:/test.sh:ro
        entrypoint: ["/test.sh"]
        depends_on:
            easyappointments:
                condition: service_healthy
            mariadb:
                condition: service_healthy
        networks:
            test_deployer_container:

    easyappointments:
        container_name: easyappointments
        image: ${IMAGE_TAG}
        depends_on:
            mariadb:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-s",
                    "--fail",
                    "http://127.0.0.1/.nginx/status",
                ]
            start_period: 5s
            interval: 15s
            timeout: 1s
        networks:
            test_deployer_container:
                aliases:
                - mariadb.local


    mariadb:
        image: mariadb:10.9
        restart: on-failure:2
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
            start_period: 10s
            interval: 15s
            timeout: 1s
            retries: 3
        networks:
            test_deployer_container:
                aliases:
                - mariadb.local
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: public
            MYSQL_USER: public
            MYSQL_PASSWORD: public

networks:
    test_deployer_container:
        driver: bridge
